import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Navbar } from '../components';
import { About, Footer, Header, Skills, Testimonial, Work } from '../container';
import styles from '../styles/Home.module.scss';

export const navItems = ['home', 'about', 'work', 'skills', 'contact'] as const;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Header />
        <About />
      </main>

      {/* 
      <About /> */}

      {/* <main>
        <Navbar />
        <Header />
        <About />
        <Work />
        <Skills />
        <Testimonial />
        <Footer />
      </main> */}
    </div>
  );
};

export default Home;
